name: Sync document

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout galia-main
        uses: actions/checkout@v2
        with:
          path: weblogic-kubernetes-operator-galia-main
          ref: galia-main
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: weblogic-kubernetes-operator-main
          ref: main
      - name: Sync
        run: |
          curPath=`pwd`
          ls
          cd weblogic-kubernetes-operator-main/documentation/3.3/content/samples/azure-kubernetes-service/
          ls
          rm -Rf *
          cp -R ${curPath}/weblogic-kubernetes-operator-galia-main/documentation/3.3/content/samples/azure-kubernetes-service/* .
          git status
          git config --global user.name "galiacheng"
          git config --global user.email "haixia.cheng@microsoft.com"
          sed -i 's/git clone --branch v{{< latestVersion >}} https:\/\/github.com\/oracle\/weblogic-kubernetes-operator.git/git clone --branch release\/3.3 https:\/\/github.com\/galiacheng\/weblogic-kubernetes-operator.git/g' domain-on-pv.md
          git add --all
          git commit -m "sync doc from galia-main"
          git push origin main
  build_and_deploy_job:
    needs: sync
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_DUNE_0DAC9090F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/documentation/3.3" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "docs" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
